language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install coveralls
  - pip install python-magic
  - pip install humanize
  - pip install .

# Command to run tests, e.g. python setup.py test
script:
  - coverage run test_imagemounter.py

# Report to coveralls
after_success:
  - coveralls
